### ISSUE TITLE
Determine licensing and ownership of repository

### ISSUE THREAD

**Issue by pharr117** [strangelove-ventures/wormchain-vps#1]
This repository contains code for spinning up GCP instances that enable devs to mainly run the Tilt tests in the wormhole codebase in a known, pre-configured environment.

We want to determine:

1. Can this repository be open sourced as is?
2. Is the Apache 2.0 License a good fit?

**Comment by pharr117** [comment]
@nik-suri curious to hear your thoughts on this issue

**Comment by cyoon0x** [comment]
Based on the current planned usage for this repo, it seems ok to open source this repo as is and Apache 2.0 License is a good fit

**Comment by pharr117** [comment]
The repo is now public, thanks @cyoon0x
